# 专用于 bp_model_mlp 的配置文件.

defaults:
  - hydra: defaults
  - wandb: defaults
  - _self_

seed: 42
device: "cuda"

input:
  path: datasets
  dataset: cifar10
  batch_size: 100 # modif 2
  val_size: 5000
  num_classes: 10

model:
  input_dim: 3072
  hidden_dim: 3072
  num_layers: 3 # modif 3
  training_type: bp

training:
  epochs: 50

  learning_rate: 1e-2 # modif 1
  lr_boundary_points: [[20, 5e-3], 1e-3]
  # final_lr: 0.4e-4
  weight_decay: 3e-4
  momentum: 0.9

  # 现在, to_validate = False 意味着不再提供 validation, 即所有训练数据全放入 training_set.
  to_validate: False
  final_test: True



