# 专用于 bp_model_mlp 的配置文件.
# define: &lr_starting_point 1e-3

defaults:
  - hydra: defaults
  - wandb: defaults
  - _self_

seed: 42
device: "cuda"

input:
  path: datasets
  dataset: mnist
  batch_size: 100 # modif 2
  val_size: 10000
  num_classes: 10

model:
  input_dim: 784
  hidden_dim: 1000  # modif 3
  num_layers: 3 # modif 4
  training_type: bp

training:
  epochs: 30  # modif 5

  learning_rate: 5e-3 # modif 1
  lr_boundary_points: [[15, 5e-3], 1e-3]
  # final_lr: 3e-4
  weight_decay: 3e-4
  momentum: 0.9

  # 现在, to_validate = False 意味着不再提供 validation, 即所有训练数据全放入 training_set.
  to_validate: False
  final_test: True

