# 专用于 bp_model_mlp 的配置文件.
# define: &lr_starting_point 1e-3

defaults:
  - hydra: defaults
  - wandb: defaults
  - _self_

seed: 42
device: "cuda"

input:
  path: datasets
  dataset: mnist
  batch_size: 100 # modif 2
  val_size: 10000
  num_classes: 10

model:
  input_dim: 784
  hidden_dim: 2000  # modif 3
  num_layers: 4 # modif 4
  training_type: bp

training:
  epochs: 60  # modif 5

  learning_rate: 0.75e-3 # modif 1
  final_lr: 3e-4
  # 简单起见, bp_mlp 网络中, lr_schedule 固定采用最原始的"过半衰减".
  weight_decay: 3e-4
  momentum: 0.9

  val_idx: -1
  final_test: True

