# Default Hyperparameters

# seed: 42
# device: "cuda"

# input:
#   path: datasets
#   batch_size: 100

# model:
#   peer_normalization: 0.03
#   momentum: 0.9

#   input_dim: 784
#   hidden_dim: 1000
#   num_layers: 3

#   goodness_type: sum
#   theta: 2.0

# training:
#   epochs: 100

#   learning_rate: 1e-3
#   weight_decay: 3e-4
#   momentum: 0.9

#   downstream_learning_rate: 1e-2
#   downstream_weight_decay: 3e-3

#   val_idx: -1
#   final_test: False

# wandb:
#   setup:
#       project: Forward-Forward
#       entity: raidriar_dai
#       mode: online
#   watch:
#       log: all
#       log_freq: 100

defaults:
  - input: cifar10
  - model: ${input}
  - training: ${input}
  - hydra: defaults
  - wandb: defaults
  - _self_

seed: 42
device: "cuda"

input:
  batch_size: 100

model:
  goodness_type: mean
  theta: 2.0  # 当 goodness_type 为 sum 时, 不用管 theta.

training:
  epochs: 200
  learning_rate: 0.002 # lr 与 batch_size 一起调参.
  final_test: True

