defaults:
  - input: mnist
  - model: ${input}
  - training: ${input}
  - hydra: defaults
  - wandb: defaults
  - _self_

seed: 42
device: "cuda"

input:
  batch_size: 100

model:
  goodness_type: sum
  theta: 2.0  # 当 goodness_type 为 sum 时, 不用管 theta.

  peer_normalization: 0.0 # modif 2: 将 peer_norm 置为0, 观察效果.

training:
  test_mode: compute_each_label
  # test_mode: one_pass_softmax

  final_test: True

  # 当 test_mode 为 compute_each_label 时, 
  # 不用管 downstream 开头的参数; 
  epochs: 100
  learning_rate: 1e-3

  downstream_learning_rate: 1e-2
  downstream_weight_decay: 3e-3

  lr_schedule: ["after_half"]
