# 已经在 model 文件夹中指明 training_type: ff

defaults:
  - input: mnist
  - model: ${input}
  - training: ${input}
  - hydra: defaults
  - wandb: defaults
  - _self_

seed: 42
device: "cuda"

input:
  batch_size: 100

model:
  num_layers: 2 # modif: 考察层数减少, 是否会改变 bp 与 ff 的 performance 差距.

  goodness_type: sum
  theta: 2.0  # 当 goodness_type 为 sum 时, 不用管 theta.

  peer_normalization: 0.0 # modif 2: 将 peer_norm 置为0, 观察效果.

  training_type: ff

training:
  test_mode: compute_each_label
  # test_mode: one_pass_softmax

  to_validate: False
  final_test: True

  epochs: 100
  learning_rate: 1e-3
  lr_boundary_points: [[50, 1e-3], 0.0]

  # 当 test_mode 为 compute_each_label 时, 
  # 不用管下面三行 downstream 开头的参数; 
  downstream_learning_rate: 1e-2
  downstream_weight_decay: 3e-3
  downstream_lr_boundary_points: [[50, 1e-2], 0.0]

